[env]
OPENAI_API_KEY = "{{exec(command='security find-generic-password -a ' ~ env.USER ~ ' -s openai-api-key -w')}}"
GEMINI_API_KEY = "{{exec(command='security find-generic-password -a ' ~ env.USER ~ ' -s gemini-api-key -w')}}"
OPENROUTER_API_KEY = "{{exec(command='security find-generic-password -a ' ~ env.USER ~ ' -s openrouter-api-key -w')}}"
JIRA_API_TOKEN = "{{exec(command='security find-generic-password -a ' ~ env.USER ~ ' -s jira-api-token -w')}}"
ANTHROPIC_API_KEY = "{{exec(command='security find-generic-password -a ' ~ env.USER ~ ' -s anthropic-api-key -w')}}"
BRAVE_API_KEY = "{{exec(command='security find-generic-password -a ' ~ env.USER ~ ' -s brave-api-key -w')}}"
EXA_API_KEY = "{{exec(command='security find-generic-password -a ' ~ env.USER ~ ' -s exa-api-key -w')}}"
GITHUB_TOKEN = "{{exec(command='gh auth token')}}"
_.path = ["~/.bun/bin"]

[settings]
idiomatic_version_file_enable_tools = ["node"]
npm.bun = true

[tools]
bun = "latest"
go = "latest"
java = "temurin-17"
node = "24"
python = "latest"
rust = "latest"
"npm:@mariozechner/pi-coding-agent" = "latest"
maven = "latest"
